name: Build and test

on: 
  push: 
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    strategy:
      matrix: 
        os: [ubuntu-latest]
        version: [17]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt'
      - name: Build project with Maven
        run: mvn -f hello-world/pom.xml --batch-mode --update-snapshots package
